// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3xaX6qA7qbEWyTZklqkjH2vDj7uBJ1vE',
    appId: '1:59115230772:android:08bbd1c4d0b4cc3d33dc61',
    messagingSenderId: '59115230772',
    projectId: 'imdfx-f37c7',
    databaseURL: 'https://imdfx-f37c7-default-rtdb.firebaseio.com',
    storageBucket: 'imdfx-f37c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqxChFN_YKIRXoxyEb5gk8Ip4U-oGeR8E',
    appId: '1:59115230772:ios:5e3b39837986661733dc61',
    messagingSenderId: '59115230772',
    projectId: 'imdfx-f37c7',
    databaseURL: 'https://imdfx-f37c7-default-rtdb.firebaseio.com',
    storageBucket: 'imdfx-f37c7.appspot.com',
    iosBundleId: 'com.dev.imedfix.app',
  );
}
